# coding: utf-8

"""
    Phaxio API

    API Definition for Phaxio

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.send_fax_response_data import SendFaxResponseData


class TestSendFaxResponseData(unittest.TestCase):
    """ SendFaxResponseData unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendFaxResponseData(self):
        """
        Test SendFaxResponseData
        """
        model = swagger_client.models.send_fax_response_data.SendFaxResponseData()


if __name__ == '__main__':
    unittest.main()
