# coding: utf-8

"""
    Phaxio API

    API Definition for Phaxio

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class DefaultApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def account_status_get(self, **kwargs):
        """
        Get account status
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.account_status_get(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: AccountStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.account_status_get_with_http_info(**kwargs)
        else:
            (data) = self.account_status_get_with_http_info(**kwargs)
            return data

    def account_status_get_with_http_info(self, **kwargs):
        """
        Get account status
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.account_status_get_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :return: AccountStatus
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method account_status_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        resource_path = '/account/status'.replace('{format}', 'json')
        path_params = {}

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='AccountStatus',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def faxes_fax_id_cancel_post(self, fax_id, **kwargs):
        """
        Cancel a Fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_cancel_post(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: SendFaxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.faxes_fax_id_cancel_post_with_http_info(fax_id, **kwargs)
        else:
            (data) = self.faxes_fax_id_cancel_post_with_http_info(fax_id, **kwargs)
            return data

    def faxes_fax_id_cancel_post_with_http_info(self, fax_id, **kwargs):
        """
        Cancel a Fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_cancel_post_with_http_info(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: SendFaxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fax_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method faxes_fax_id_cancel_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'fax_id' is set
        if ('fax_id' not in params) or (params['fax_id'] is None):
            raise ValueError("Missing the required parameter `fax_id` when calling `faxes_fax_id_cancel_post`")


        collection_formats = {}

        resource_path = '/faxes/{faxId}/cancel'.replace('{format}', 'json')
        path_params = {}
        if 'fax_id' in params:
            path_params['faxId'] = params['fax_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='SendFaxResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def faxes_fax_id_delete(self, fax_id, **kwargs):
        """
        Delete a fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_delete(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: FailureResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.faxes_fax_id_delete_with_http_info(fax_id, **kwargs)
        else:
            (data) = self.faxes_fax_id_delete_with_http_info(fax_id, **kwargs)
            return data

    def faxes_fax_id_delete_with_http_info(self, fax_id, **kwargs):
        """
        Delete a fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_delete_with_http_info(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: FailureResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fax_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method faxes_fax_id_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'fax_id' is set
        if ('fax_id' not in params) or (params['fax_id'] is None):
            raise ValueError("Missing the required parameter `fax_id` when calling `faxes_fax_id_delete`")


        collection_formats = {}

        resource_path = '/faxes/{faxId}'.replace('{format}', 'json')
        path_params = {}
        if 'fax_id' in params:
            path_params['faxId'] = params['fax_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='FailureResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def faxes_fax_id_file_delete(self, fax_id, **kwargs):
        """
        Delete a fax file
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_file_delete(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: FailureResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.faxes_fax_id_file_delete_with_http_info(fax_id, **kwargs)
        else:
            (data) = self.faxes_fax_id_file_delete_with_http_info(fax_id, **kwargs)
            return data

    def faxes_fax_id_file_delete_with_http_info(self, fax_id, **kwargs):
        """
        Delete a fax file
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_file_delete_with_http_info(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: FailureResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fax_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method faxes_fax_id_file_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'fax_id' is set
        if ('fax_id' not in params) or (params['fax_id'] is None):
            raise ValueError("Missing the required parameter `fax_id` when calling `faxes_fax_id_file_delete`")


        collection_formats = {}

        resource_path = '/faxes/{faxId}/file'.replace('{format}', 'json')
        path_params = {}
        if 'fax_id' in params:
            path_params['faxId'] = params['fax_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'DELETE',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='FailureResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def faxes_fax_id_file_get(self, fax_id, **kwargs):
        """
        Get fax content file or thumbnail
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_file_get(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :param str thumbnail: if set, request a thumbnail only in specified size
        :return: file
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.faxes_fax_id_file_get_with_http_info(fax_id, **kwargs)
        else:
            (data) = self.faxes_fax_id_file_get_with_http_info(fax_id, **kwargs)
            return data

    def faxes_fax_id_file_get_with_http_info(self, fax_id, **kwargs):
        """
        Get fax content file or thumbnail
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_file_get_with_http_info(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :param str thumbnail: if set, request a thumbnail only in specified size
        :return: file
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fax_id', 'thumbnail']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method faxes_fax_id_file_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'fax_id' is set
        if ('fax_id' not in params) or (params['fax_id'] is None):
            raise ValueError("Missing the required parameter `fax_id` when calling `faxes_fax_id_file_get`")


        collection_formats = {}

        resource_path = '/faxes/{faxId}/file'.replace('{format}', 'json')
        path_params = {}
        if 'fax_id' in params:
            path_params['faxId'] = params['fax_id']

        query_params = {}
        if 'thumbnail' in params:
            query_params['thumbnail'] = params['thumbnail']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/octet-stream'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='file',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def faxes_fax_id_get(self, fax_id, **kwargs):
        """
        Get Fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_get(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: GetFaxInfoResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.faxes_fax_id_get_with_http_info(fax_id, **kwargs)
        else:
            (data) = self.faxes_fax_id_get_with_http_info(fax_id, **kwargs)
            return data

    def faxes_fax_id_get_with_http_info(self, fax_id, **kwargs):
        """
        Get Fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_get_with_http_info(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: GetFaxInfoResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fax_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method faxes_fax_id_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'fax_id' is set
        if ('fax_id' not in params) or (params['fax_id'] is None):
            raise ValueError("Missing the required parameter `fax_id` when calling `faxes_fax_id_get`")


        collection_formats = {}

        resource_path = '/faxes/{faxId}'.replace('{format}', 'json')
        path_params = {}
        if 'fax_id' in params:
            path_params['faxId'] = params['fax_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='GetFaxInfoResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def faxes_fax_id_resend_post(self, fax_id, **kwargs):
        """
        Resend a Fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_resend_post(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: SendFaxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.faxes_fax_id_resend_post_with_http_info(fax_id, **kwargs)
        else:
            (data) = self.faxes_fax_id_resend_post_with_http_info(fax_id, **kwargs)
            return data

    def faxes_fax_id_resend_post_with_http_info(self, fax_id, **kwargs):
        """
        Resend a Fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_fax_id_resend_post_with_http_info(fax_id, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int fax_id: Fax ID (required)
        :return: SendFaxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['fax_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method faxes_fax_id_resend_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'fax_id' is set
        if ('fax_id' not in params) or (params['fax_id'] is None):
            raise ValueError("Missing the required parameter `fax_id` when calling `faxes_fax_id_resend_post`")


        collection_formats = {}

        resource_path = '/faxes/{faxId}/resend'.replace('{format}', 'json')
        path_params = {}
        if 'fax_id' in params:
            path_params['faxId'] = params['fax_id']

        query_params = {}

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='SendFaxResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def faxes_get(self, **kwargs):
        """
        List faxes in date range
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_get(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str created_before: End of the range
        :param str created_after: Beginning of the range
        :param str direction: Limits results to faxes with the specified direction
        :param str status: Limits results to faxes with the specified status
        :param str phone_number: A phone number in E.164 format that you want to use to filter results.
        :param int per_page: How many records to return per page
        :param int page: Page number to return
        :return: GetFaxesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.faxes_get_with_http_info(**kwargs)
        else:
            (data) = self.faxes_get_with_http_info(**kwargs)
            return data

    def faxes_get_with_http_info(self, **kwargs):
        """
        List faxes in date range
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_get_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str created_before: End of the range
        :param str created_after: Beginning of the range
        :param str direction: Limits results to faxes with the specified direction
        :param str status: Limits results to faxes with the specified status
        :param str phone_number: A phone number in E.164 format that you want to use to filter results.
        :param int per_page: How many records to return per page
        :param int page: Page number to return
        :return: GetFaxesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['created_before', 'created_after', 'direction', 'status', 'phone_number', 'per_page', 'page']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method faxes_get" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        resource_path = '/faxes'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'created_before' in params:
            query_params['created_before'] = params['created_before']
        if 'created_after' in params:
            query_params['created_after'] = params['created_after']
        if 'direction' in params:
            query_params['direction'] = params['direction']
        if 'status' in params:
            query_params['status'] = params['status']
        if 'phone_number' in params:
            query_params['phone_number'] = params['phone_number']
        if 'per_page' in params:
            query_params['per_page'] = params['per_page']
        if 'page' in params:
            query_params['page'] = params['page']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='GetFaxesResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def faxes_post(self, to, **kwargs):
        """
        Create and Send a Fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_post(to, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str to: phone number (required)
        :param str direction: Set to 'received' to receive test fax.
        :param list[file] file: file to send
        :param list[str] content_url: url of file to send
        :param str header_text: Text that appears at the top of each page
        :param int batch_delay: Number of seconds to wait before sending batch
        :param bool batch_collision_avoidance: When batch_delay is set, fax will be blocked until the receiving machine is no longer busy
        :param str callback_url: Overrides global callback URL
        :param int cancel_timeout: Number of minutes to wait for successful send before cancelling fax
        :param int tag: Number of minutes to wait for successful send before cancelling fax
        :param str caller_id: Number to use for caller ID
        :param str test_fail: When sending a test fax, if this is set it will simulate the failure type specified
        :return: SendFaxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.faxes_post_with_http_info(to, **kwargs)
        else:
            (data) = self.faxes_post_with_http_info(to, **kwargs)
            return data

    def faxes_post_with_http_info(self, to, **kwargs):
        """
        Create and Send a Fax
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.faxes_post_with_http_info(to, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param str to: phone number (required)
        :param str direction: Set to 'received' to receive test fax.
        :param list[file] file: file to send
        :param list[str] content_url: url of file to send
        :param str header_text: Text that appears at the top of each page
        :param int batch_delay: Number of seconds to wait before sending batch
        :param bool batch_collision_avoidance: When batch_delay is set, fax will be blocked until the receiving machine is no longer busy
        :param str callback_url: Overrides global callback URL
        :param int cancel_timeout: Number of minutes to wait for successful send before cancelling fax
        :param int tag: Number of minutes to wait for successful send before cancelling fax
        :param str caller_id: Number to use for caller ID
        :param str test_fail: When sending a test fax, if this is set it will simulate the failure type specified
        :return: SendFaxResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['to', 'direction', 'file', 'content_url', 'header_text', 'batch_delay', 'batch_collision_avoidance', 'callback_url', 'cancel_timeout', 'tag', 'caller_id', 'test_fail']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method faxes_post" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'to' is set
        if ('to' not in params) or (params['to'] is None):
            raise ValueError("Missing the required parameter `to` when calling `faxes_post`")


        collection_formats = {}

        resource_path = '/faxes'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'direction' in params:
            query_params['direction'] = params['direction']

        header_params = {}

        form_params = []
        local_var_files = {}
        if 'to' in params:
            form_params.append(('to', params['to']))
        if 'file' in params:
            local_var_files['file[]'] = params['file']
            collection_formats['file[]'] = 'multi'
        if 'content_url' in params:
            form_params.append(('content_url[]', params['content_url']))
            collection_formats['content_url[]'] = 'multi'
        if 'header_text' in params:
            form_params.append(('header_text', params['header_text']))
        if 'batch_delay' in params:
            form_params.append(('batch_delay', params['batch_delay']))
        if 'batch_collision_avoidance' in params:
            form_params.append(('batch_collision_avoidance', params['batch_collision_avoidance']))
        if 'callback_url' in params:
            form_params.append(('callback_url', params['callback_url']))
        if 'cancel_timeout' in params:
            form_params.append(('cancel_timeout', params['cancel_timeout']))
        if 'tag' in params:
            form_params.append(('tag', params['tag']))
        if 'caller_id' in params:
            form_params.append(('caller_id', params['caller_id']))
        if 'test_fail' in params:
            form_params.append(('test_fail', params['test_fail']))

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.\
            select_header_content_type(['multipart/form-data'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'POST',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='SendFaxResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)

    def public_countries_get(self, **kwargs):
        """
        Returns a list of supported countries for sending and receiving faxes
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.public_countries_get(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int per_page: How many records to return per page
        :param int page: Page number to return
        :return: GetCountriesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.public_countries_get_with_http_info(**kwargs)
        else:
            (data) = self.public_countries_get_with_http_info(**kwargs)
            return data

    def public_countries_get_with_http_info(self, **kwargs):
        """
        Returns a list of supported countries for sending and receiving faxes
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.public_countries_get_with_http_info(callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param int per_page: How many records to return per page
        :param int page: Page number to return
        :return: GetCountriesResponse
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['per_page', 'page']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method public_countries_get" % key
                )
            params[key] = val
        del params['kwargs']


        collection_formats = {}

        resource_path = '/public/countries'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'per_page' in params:
            query_params['per_page'] = params['per_page']
        if 'page' in params:
            query_params['page'] = params['page']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = ['UserSecurity']

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='GetCountriesResponse',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
