# coding: utf-8

"""
    Phaxio API

    API Definition for Phaxio

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.list_phone_numbers_response import ListPhoneNumbersResponse


class TestListPhoneNumbersResponse(unittest.TestCase):
    """ ListPhoneNumbersResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListPhoneNumbersResponse(self):
        """
        Test ListPhoneNumbersResponse
        """
        model = swagger_client.models.list_phone_numbers_response.ListPhoneNumbersResponse()


if __name__ == '__main__':
    unittest.main()
