# coding: utf-8

"""
    Phaxio API

    API Definition for Phaxio

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.account_status import AccountStatus


class TestAccountStatus(unittest.TestCase):
    """ AccountStatus unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountStatus(self):
        """
        Test AccountStatus
        """
        model = swagger_client.models.account_status.AccountStatus()


if __name__ == '__main__':
    unittest.main()
