# coding: utf-8

"""
    Phaxio API

    API Definition for Phaxio

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.phone_number_response import PhoneNumberResponse


class TestPhoneNumberResponse(unittest.TestCase):
    """ PhoneNumberResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPhoneNumberResponse(self):
        """
        Test PhoneNumberResponse
        """
        model = swagger_client.models.phone_number_response.PhoneNumberResponse()


if __name__ == '__main__':
    unittest.main()
