# coding: utf-8

"""
    Phaxio API

    API Definition for Phaxio

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.account_status import AccountStatus
from .models.account_status_data import AccountStatusData
from .models.error import Error
from .models.failure_response import FailureResponse
from .models.fax_info import FaxInfo
from .models.fax_info_data import FaxInfoData
from .models.recipient import Recipient
from .models.send_fax_response import SendFaxResponse
from .models.send_fax_response_data import SendFaxResponseData
from .models.status import Status

# import apis into sdk package
from .apis.default_api import DefaultApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
