# coding: utf-8

"""
    Phaxio API

    API Definition for Phaxio

    OpenAPI spec version: 2.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from .account_status import AccountStatus
from .account_status_data import AccountStatusData
from .error import Error
from .failure_response import FailureResponse
from .fax_info import FaxInfo
from .fax_info_data import FaxInfoData
from .recipient import Recipient
from .send_fax_response import SendFaxResponse
from .send_fax_response_data import SendFaxResponseData
from .status import Status
